version: '3.7'
services:
    redis:
      image: docker.io/bitnami/redis:6.2
      environment:
        # ALLOW_EMPTY_PASSWORD is recommended only for development.
        - ALLOW_EMPTY_PASSWORD=yes
        - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      ports:
        - '6379:6379'
      volumes:
        - './redis-data:/bitnami/redis/data'