name: Build Projects

on:
  workflow_call:
    inputs:
      BuildVersion:
        required: true
        type: string
      isRelease:
        required: true
        type: boolean
    secrets:
      token:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      BuildConfiguration: Release

    steps:
    - name: Git Check out
      uses: actions/checkout@v2
    
    # - name: Start dependencies (docker-compose)
    #   run: docker-compose up -d

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Add Package Source
      run: dotnet nuget add source --username malweka --password ${{ secrets.token }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/malweka/index.json"
    - name: Restore dependencies
      run: dotnet restore src/GoliathUtils.sln
    - name: Build
      run: dotnet build --no-restore --configuration $BuildConfiguration /p:DefineConstants=INTEGRATION -p:PackageVersion=${{ inputs.BuildVersion }}.$GITHUB_RUN_NUMBER -p:Version=${{ inputs.BuildVersion }}.$GITHUB_RUN_NUMBER -p:AssemblyVersion=${{ inputs.BuildVersion }}.$GITHUB_RUN_NUMBER -p:FileVersion=${{ inputs.BuildVersion }}.$GITHUB_RUN_NUMBER src/GoliathUtils.sln
    - name: Test
      if: ${{ inputs.isRelease }} == false
      run: dotnet test --no-build --configuration $BuildConfiguration --verbosity normal /p:DefineConstants=INTEGRATION src/Goliath.Utilities.Tests/Goliath.Utilities.Tests.csproj
    - name: Package Push src/Goliath.Utilities/bin/Release/Goliath.Utilities
      if: ${{ inputs.isRelease }} == true
      run: dotnet nuget push --api-key ${{ secrets.token }} --source "github" src/Goliath.Utilities/bin/$BuildConfiguration/Goliath.Utilities.${{ inputs.BuildVersion }}.$GITHUB_RUN_NUMBER.nupkg
