name: Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  call-build-Workflow:
    uses: ./.github/workflows/build.yml
    with:
      BuildVersion: 3.0.0
      isRelease: false
    secrets:
      token: ${{ secrets.PACKAGETOKEN }}