name: Package and Push

on:
  push:
    branches: [ master ]

jobs:
  call-build-Workflow:
    uses: ./.github/workflows/build.yml
    with:
      BuildVersion: 3.0.1
    secrets:
      token: ${{ secrets.PACKAGETOKEN }}

  Deploy:
   runs-on: ubuntu-latest
   needs: call-build-Workflow
   steps:
   - name: Setup .NET
     uses: actions/setup-dotnet@v3
     with:
      dotnet-version: 6.0.x
   - name: Add Package Source
     run: dotnet nuget add source --username malweka --password ${{ secrets.PACKAGETOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/malweka/index.json"
   - name: Download Artifacts
     uses: actions/download-artifact@v3
     with:
       name: goliath-utilities
       path: packages

   - name: Package Push src/Goliath.Utilities/bin/Release/Goliath.Utilities
     run: find packages/ -type f -name "*.nupkg" -exec dotnet nuget push --api-key ${{ secrets.PACKAGETOKEN }} --source "github" {} \;